github:
  branch_name: main
  tooling_branch_name: main
bot:
  inspection: update-grayskull
  automerge: true
  check_solvable: true
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
